export const elements = [
    { id: 'A', text: 'Option A', checked: true },
    { id: 'B1', text: 'Option B', parentId: 'A' },
    { id: 'B2', text: 'Option B', parentId: 'A' },
    { id: 'B3', text: 'Option B', parentId: 'A' },
    { id: 'C', text: 'Option C', checked: true },
    { id: 'D1', text: 'Option D', parentId: 'C' },
    { id: 'D2', text: 'Option D', parentId: 'C' },
    { id: 'D3', text: 'Option D', parentId: 'C' },
    { id: 'E', text: 'Option E', checked: false },
    { id: 'F1', text: 'Option F', parentId: 'E' },
    { id: 'F11', text: 'Option FF', parentId: 'F1' },
    { id: 'F111', text: 'Option FFF', parentId: 'F11' },
    { id: 'F112', text: 'Option FFF', parentId: 'F11', checked: true },
    { id: 'F113', text: 'Option FFF', parentId: 'F11' },
    { id: 'F12', text: 'Option FF', parentId: 'F1' },
    { id: 'F13', text: 'Option FF', parentId: 'F1', checked: true },
    { id: 'F14', text: 'Option FF', parentId: 'F1' },
    { id: 'F2', text: 'Option F', parentId: 'E' },
    { id: 'F3', text: 'Option F', parentId: 'E' },
];
